### ISSUE TITLE
Mix project references out of tree paths

### ISSUE THREAD

**Issue by jtdowney** [jschneider1207/hkdf#2]
It looks like perhaps this code was extracted from a larger project because the mix.exs references paths up one directory. When you clone the repository to run `mix test` it is clear to see:

```
$ mix test
** (File.Error) could not read file "/Users/config/config.exs": no such file or directory
    (elixir 1.11.0) lib/file.ex:353: File.read!/1
    (elixir 1.11.0) lib/config/reader.ex:104: Config.Reader.read_imports!/2
    (mix 1.11.0) lib/mix/tasks/loadconfig.ex:49: Mix.Tasks.Loadconfig.load_compile/1
    (mix 1.11.0) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.0) lib/mix/cli.ex:83: Mix.CLI.run_task/2```

**Comment by jschneider1207** [comment]
Fixed this, thank you
